[package]
name = "e2k"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = "1.0.95"
educe = "0.6.0"
itertools = "0.14.0"
ndarray = "0.16.1"
ndarray-npz = "0.3.0"
num-traits = "0.2.19"
