[package]
name = "e2k"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
anyhow = "1.0.95"
duplicate = "2.0.0"
educe = "0.6.0"
itertools = "0.14.0"
ndarray = "0.16.1"
num-traits = "0.2.19"
rand = "0.9.0"
