version: "3"

tasks:
  generate_constants:
    cmds:
      - cd tasks && uv run python3 ./generate_constants.py
      - cargo fmt
  benchmark:
    cmds:
      - cd tasks && uv run pytest --benchmark-json=benchmark.json
      - cargo bench
      - cd tasks && uv run python3 ./plot_benchmark.py
