[package]
name = "e2k-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "e2k_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
e2k = { path = "../e2k-rs" }
