version: "3"

tasks:
  build:
    cmds:
      - rm -rf pkg
      - cd ../e2k-rs && cargo build
      - cd ../e2k-rs && task generate_about && cp ./NOTICE.md ../e2k-js/js/NOTICE.md
      - wasm-pack build -t web
      - cd js && pnpm run build
